### ISSUE TITLE
Bundle is not compatible with Symfony 4.4

### ISSUE THREAD

**Issue by N0ps32** [mtarld/symbok-bundle#22]
The Bundle breaks with symfony 4.4 because the AutoloadService tries to use ```Symfony\Component\Debug\DebugClassLoader```

which was replaced by ```Symfony\Component\ErrorHandler\DebugClassLoader``` in Symfony 4.4

I think the best way to fix this is to check for both for now until the old class is removed to provide backwards compatibility.

**Comment by mtarld** [comment]
Hi @N0ps32 , 
I'm currently working on an huge revamp of that bundle which will be available during the week.
Could you please try it with the 2.0 version ?
