### ISSUE TITLE
Bundle fails on symfony 4.4 when trying to eval generated class

### ISSUE THREAD

**Issue by N0ps32** [mtarld/symbok-bundle#23]
```
Warning: filemtime(): stat failed for /app/vendor/mtarld/symbok-bundle/Cache/PhpFileCache.php(34) : eval()'d code
```
This also happens when caching is disabled.

**Comment by mtarld** [comment]
Hi @N0ps32 , 
I'm currently working on an huge revamp of that bundle which will be available during the week.
Could you please try it with the 2.0 branch ?
