### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by carlobeltrame** [mtarld/symbok-bundle#58]
Does this bundle support PHP 8? I was able to install it and use the basic functionality using `--ignore-platform-reqs`, but it would be nice if the bundle could be specified to support PHP 8.

**Comment by mtarld** [comment]
Hi @carlobeltrame, unfortunately, PHP 8 isn't supported yet. 
I planned to do it but I don't have enough time at the moment.
Any PR would be really appreciated!

**Comment by carlobeltrame** [comment]
Do you have any pointers on which parts of the package do not support php 8? I was only using getter and setter so far, and those seemed to work alright.

**Comment by mtarld** [comment]
Actually, I think (but I haven't tested it yet) that everything should work as expected with PHP8.
The thing is, if we wanna support PHP8, we should be able to support one of the great things provided by PHP8: attributes :wink: 
The rest won't need to change IMHO

WDYT?

**Comment by carlobeltrame** [comment]
I tried updating the dev dependencies to allow versions that support PHP 8. Locally, I got the tests to work, but on GitHub Actions some of them fail because of autoloader internals which I don't know enough about: https://github.com/carlobeltrame/symbok-bundle/tree/php-8-support

Attributes would be nice of course, and from what I've seen they are not too hard to support if you already have a good system for reading annotations. But I'd do that in a second step, once there is a version that can be installed with PHP 8 at all.

**Comment by mtarld** [comment]
Indeed this is strange... I'll try to have a look ASAP

**Comment by joerndyherrn** [comment]
Any news here? :)

**Comment by carlobeltrame** [comment]
Since we use php 8 in my project, I opted out of using symbok, and I did not personally pursue this any further.

**Comment by xShazzy** [comment]
> Since we use php 8 in my project, I opted out of using symbok, and I did not personally pursue this any further.

What do you mean? How does php 8 discredit symbok? I'm just wondering if missed anything.

**Comment by carlobeltrame** [comment]
As the @mtarld wrote a year ago, symbok does not support php 8. The last commit to symbok was made 2 years ago, and the help from @mtarld never arrived until now. So I presume php 8 still is not supported, and thus my php 8 project cannot use symbok.

**Comment by nelsw** [comment]
[Lombok php](https://github.com/MarcinOrlowski/lombok-php) looks promising ...

**Comment by mtarld** [comment]
Indeed, thank you for the research, I didn't manage to find any time to work on that repository.
And with PHP 8.1 and the emergence of public read-only properties, this bundle doesn't make any more sense to me.

Therefore I gonna archive it. Anyone can feel free to fork it and make it evolve and live (I'd be really happy if something like that happens :wink:)
